### ISSUE TITLE
Why the page is blank ?

### ISSUE THREAD

**Issue by freemank1224** [microsoft/data-formulator#47]
After successfully installed dependencies, I run the `data_formulator`, it prompts a new browser window but nothing displayed on the screen.  The info on command window is :
` * Serving Flask app 'data_formulator.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://198.18.0.1:5000
Press CTRL+C to quit
C:\Users\dyson\miniconda3\envs\dataf\lib\site-packages\data_formulator\dist
127.0.0.1 - - [01/Nov/2024 16:46:55] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [01/Nov/2024 16:46:55] "GET /DataFormulator.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Nov/2024 16:46:55] "GET /assets/index-XIyIzJet.css HTTP/1.1" 304 -
C:\Users\dyson\miniconda3\envs\dataf\lib\site-packages\data_formulator\dist
127.0.0.1 - - [01/Nov/2024 16:47:08] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [01/Nov/2024 16:47:08] "GET /DataFormulator.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Nov/2024 16:47:08] "GET /assets/index-XIyIzJet.css HTTP/1.1" 304 -`

**Comment by Chenglong-MS** [comment]
Interesting! I don't expect this to happen.

Normally the status code should be:
```
127.0.0.1 - - [01/Nov/2024 10:03:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2024 10:03:48] "GET /assets/index-XIyIzJet.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2024 10:03:48] "GET /DataFormulator.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2024 10:03:48] "GET /favicon.ico HTTP/1.1" 200 -
```

We can try:
(1) clear the browser cache and retry http://127.0.0.1:5000/ (or maybe open it in a different browser)
(2) you can also take a screenshot of the "inspect" result from the webpage (right click on the blank webpage, and in the context menu click "console" tab once the developer tool opoens), I'm curious what's the error message there.
(3) if that's still an issue, you could try CodeSpaces (https://codespaces.new/microsoft/data-formulator?quickstart=1) as well!

![Image](https://github.com/user-attachments/assets/257331a3-9037-4af2-a8a1-72409d838b90)

**Comment by nicho2** [comment]
Hello,
I have the same thing with this error in the console:

DataFormulator.js:1 
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by danmarshall** [comment]
@freemank1224 @nicho2 can you try adding this line to your app.py and see if it fixes the issue?

```py
import mimetypes
mimetypes.add_type('application/javascript', '.js')
```

**Comment by Chenglong-MS** [comment]
This is the artifact from Dan's build:

You can check if this build fixes the issue by:
1. download the tar.gz
2. install it with 'pip install --upgrade --force-reinstall data_formulator-0.1.3.3.tar.gz'
3. then run `data_formulator`

If this build looks good, we can merge Dan's PR (https://github.com/microsoft/data-formulator/pull/48)

[data_formulator-0.1.3.3.tar.gz](https://github.com/user-attachments/files/17625396/data_formulator-0.1.3.3.tar.gz)

**Comment by freemank1224** [comment]
> [@freemank1224](https://github.com/freemank1224) [@nicho2](https://github.com/nicho2) can you try adding this line to your app.py and see if it fixes the issue?
> 
> import mimetypes
> mimetypes.add_type('application/javascript', '.js')

Thanks for this but nothing happened

**Comment by freemank1224** [comment]
> This is the artifact from Dan's build:
> 
> You can check if this build fixes the issue by:
> 
> 1. download the tar.gz
> 2. install it with 'pip install --upgrade --force-reinstall data_formulator-0.1.3.3.tar.gz'
> 3. then run `data_formulator`
> 
> If this build looks good, we can merge Dan's PR ([#48](https://github.com/microsoft/data-formulator/pull/48))
> 
> [data_formulator-0.1.3.3.tar.gz](https://github.com/user-attachments/files/17625396/data_formulator-0.1.3.3.tar.gz)

This really NICE! It works after I followed this instructions
